// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cashback.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvedOrderCount = `-- name: ApprovedOrderCount :one
SELECT count(*) FROM orders WHERE user_id=$1 AND status='approved'
`

func (q *Queries) ApprovedOrderCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, approvedOrderCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const cashbackTiers = `-- name: CashbackTiers :many
SELECT tier_code,min_approved_orders,min_share_bps,max_share_bps FROM cashback_tiers WHERE policy_id=$1 ORDER BY min_approved_orders
`

type CashbackTiersRow struct {
	TierCode          string
	MinApprovedOrders int64
	MinShareBps       int32
	MaxShareBps       int32
}

func (q *Queries) CashbackTiers(ctx context.Context, policyID pgtype.UUID) ([]CashbackTiersRow, error) {
	rows, err := q.db.Query(ctx, cashbackTiers, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashbackTiersRow
	for rows.Next() {
		var i CashbackTiersRow
		if err := rows.Scan(
			&i.TierCode,
			&i.MinApprovedOrders,
			&i.MinShareBps,
			&i.MaxShareBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const currentCashbackPolicy = `-- name: CurrentCashbackPolicy :one
SELECT id::text,created_at,tax_bps FROM cashback_policies WHERE mode='tiered' ORDER BY created_at DESC,id DESC LIMIT 1
`

type CurrentCashbackPolicyRow struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	TaxBps    int32
}

func (q *Queries) CurrentCashbackPolicy(ctx context.Context) (CurrentCashbackPolicyRow, error) {
	row := q.db.QueryRow(ctx, currentCashbackPolicy)
	var i CurrentCashbackPolicyRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.TaxBps)
	return i, err
}
