// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AffiliateChannel struct {
	ID       string
	Name     string
	Status   string
	Settings []byte
}

type AffiliateLink struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Channel      string
	OriginalUrl  string
	AffiliateUrl string
	TrackingCode string
	PolicyID     pgtype.UUID
	ItemID       pgtype.Text
	CreatedAt    pgtype.Timestamptz
	TierCode     pgtype.Text
	MinShareBps  int32
	MaxShareBps  int32
}

type AppSetting struct {
	ID       bool
	Settings []byte
}

type AuditLog struct {
	ID        pgtype.UUID
	ActorID   pgtype.UUID
	Action    string
	Resource  string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

type AuthIdentity struct {
	Subject string
	UserID  pgtype.UUID
}

type CashbackPolicy struct {
	ID           pgtype.UUID
	SharePercent pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
	Mode         string
}

type CashbackTier struct {
	PolicyID          pgtype.UUID
	TierCode          string
	MinApprovedOrders int64
	MinShareBps       int32
	MaxShareBps       int32
}

type Checkin struct {
	UserID  pgtype.UUID
	Day     pgtype.Date
	Streak  int32
	Award   int32
	AwardXu pgtype.Int8
}

type CoinAccount struct {
	UserID  pgtype.UUID
	Balance int64
	Streak  int32
	Best    int32
	LastDay pgtype.Date
}

type CoinTransaction struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Reference   string
	Amount      int64
	Description string
	CreatedAt   pgtype.Timestamptz
}

type Deal struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Channel   string
	Body      string
	Hidden    bool
	Deleted   bool
	Reason    string
	CreatedAt pgtype.Timestamptz
}

type DealLike struct {
	DealID pgtype.UUID
	UserID pgtype.UUID
}

type GiftCatalog struct {
	ID      string
	Name    string
	Channel string
	Cost    int64
	Stock   int32
	Active  bool
}

type GiftRedemption struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	GiftID        string
	Cost          int64
	Status        string
	VoucherCipher pgtype.Text
	Reason        string
	CreatedAt     pgtype.Timestamptz
	CostXu        pgtype.Int8
	CostUnit      string
}

type IdempotencyRecord struct {
	UserID      pgtype.UUID
	Key         string
	Operation   string
	PayloadHash string
	Response    []byte
	CreatedAt   pgtype.Timestamptz
}

type ImportBatch struct {
	ID         pgtype.UUID
	ActorID    pgtype.UUID
	Filename   string
	FileHash   string
	Mapping    []byte
	Status     string
	LeaseUntil pgtype.Timestamptz
	Attempts   int32
	Error      pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type ImportRow struct {
	BatchID   pgtype.UUID
	RowNumber int32
	Payload   []byte
	Status    string
	Error     pgtype.Text
}

type InternalCredential struct {
	UserID       pgtype.UUID
	Username     string
	PasswordHash string
	MustChange   bool
}

type Notification struct {
	ID          pgtype.UUID
	RecipientID pgtype.UUID
	Title       string
	Body        string
	Deleted     bool
	CreatedAt   pgtype.Timestamptz
}

type NotificationReceipt struct {
	NotificationID pgtype.UUID
	UserID         pgtype.UUID
	ReadAt         pgtype.Timestamptz
}

type OauthRequest struct {
	StateHash string
	Nonce     string
	Verifier  string
	ExpiresAt pgtype.Timestamptz
}

type Order struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	LinkID       pgtype.UUID
	PolicyID     pgtype.UUID
	Channel      string
	Publisher    string
	ExternalID   string
	LineID       string
	ProductName  string
	Value        int64
	Commission   int64
	Cashback     int64
	Status       string
	OrderedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	SourceStatus string
	ApprovedAt   pgtype.Timestamptz
	TierCode     pgtype.Text
	ShareBps     int32
}

type OrderEvent struct {
	ID        pgtype.UUID
	OrderID   pgtype.UUID
	ActorID   pgtype.UUID
	Action    string
	Reason    string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

type OrderItem struct {
	ID       pgtype.UUID
	OrderID  pgtype.UUID
	ItemID   pgtype.Text
	Quantity int32
}

type OutboxEvent struct {
	ID         pgtype.UUID
	Kind       string
	Payload    []byte
	Status     string
	LeaseUntil pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type PrivateFile struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	Purpose     string
	Name        string
	Path        string
	ContentType string
	CreatedAt   pgtype.Timestamptz
}

type ProductCheck struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ItemID    string
	ShopID    string
	Result    []byte
	CreatedAt pgtype.Timestamptz
}

type RateLimitBucket struct {
	Key       string
	WindowID  int64
	Count     int32
	ExpiresAt pgtype.Timestamptz
}

type RewardPolicy struct {
	ID       string
	Settings []byte
}

type Session struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	TokenHash         string
	CsrfHash          string
	CsrfToken         string
	ReauthenticatedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	Role         string
	Blocked      bool
	TrackingCode string
	CreatedAt    pgtype.Timestamptz
	// AES-GCM encrypted JSON: bank, account, holder. Private payout profile, separate from display name.
	BankDetails pgtype.Text
}

type UserPermission struct {
	UserID     pgtype.UUID
	Permission string
}

type WalletAccount struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	Kind    string
	Balance int64
}

type WalletEntry struct {
	ID            pgtype.UUID
	TransactionID pgtype.UUID
	AccountID     pgtype.UUID
	Amount        int64
}

type WalletTransaction struct {
	ID          pgtype.UUID
	Reference   string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type WalletUnification struct {
	ID          bool
	ConvertedAt pgtype.Timestamptz
}

type Withdrawal struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Amount        int64
	Bank          string
	BankDetails   string
	Status        string
	ProcessorID   pgtype.UUID
	BankReference pgtype.Text
	EvidencePath  pgtype.Text
	Reason        string
	CreatedAt     pgtype.Timestamptz
}
