// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id::text,name,email,role,blocked,tracking_code,created_at FROM users WHERE id=$1
`

type GetUserRow struct {
	ID           string
	Name         string
	Email        string
	Role         string
	Blocked      bool
	TrackingCode string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Blocked,
		&i.TrackingCode,
		&i.CreatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :many
SELECT kind,balance FROM wallet_accounts WHERE user_id=$1
`

type GetWalletRow struct {
	Kind    string
	Balance int64
}

func (q *Queries) GetWallet(ctx context.Context, userID pgtype.UUID) ([]GetWalletRow, error) {
	rows, err := q.db.Query(ctx, getWallet, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWalletRow
	for rows.Next() {
		var i GetWalletRow
		if err := rows.Scan(&i.Kind, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id,name,status FROM affiliate_channels ORDER BY id
`

type ListChannelsRow struct {
	ID     string
	Name   string
	Status string
}

func (q *Queries) ListChannels(ctx context.Context) ([]ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
